# -*- coding: utf-8 -*-
"""IndividualPDFScraping

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ShWvJ4hV57ZBHyDqZcgwGHV3V0Y_cOBe
"""

!pip install pdfplumber -q

import re
import pdfplumber
import pandas as pd

pdf = pdfplumber.open("/content/A340_TCDS_EASA.A.015_-_Issue_27.pdf")
page = pdf.pages[2]
text = page.extract_text()

print(text)

tcds_no_re = re.compile(r'^\ATCDS*')

for line in text.split('\n'):
  if tcds_no_re.match(line):
    print(line)

for line in text.split('\n'):
  if tcds_no_re.match(line):
    tcds_no, *tch = re.split(r'^\+',line,2)
    print(tcds_no, *tch)

issue_date_re = re.compile(r'^\AIssue*')

for line in text.split('\n'):
  if issue_date_re.match(line):
    print(line)

models_re = re.compile(r'A{3}-{3}')

for line in text.split('\n'):
  if models_re.match(line):
    print(line)

models = re.findall("A\d{3}-\d{3}", text)
print(models)